Dev
firesworder/password_saver pull request #1
Opened 2023-09-08 17:20 UTC by firesworder

Тесты пришлось удалить из за слишком значимых изменений в программе.
Протестировал руками перед отправкой

2023-09-09 14:29 UTC, tmvrus requested changes
<img width="726" alt="image" src="https://github.com/firesworder/password_saver/assets/554425/99fff017-f268-41f3-b9a1-2cdb1c5438d2">

2023-09-20 14:46 UTC, tmvrus requested changes
К работе очень много замечаний:
- нет внятной инструкции для запуска
- механизм авторизации не переживет рестарта приложения и не приспособлен к работе в распределенном окружении
- race condition
- mock серверной части по какой-то причине создан в ручную, использование строго ограничено предустановленными данными
- повсеместно игнорируются ошибки
- слой хранения данных занимается еще и шифрование/дешифрованием
- злоупотребление Fatal
- все еще есть сущности без документации

2023-09-20 14:46 UTC, tmvrus commented on internal/agent/agentcommands/updatedata_test.go
> +		enterBinaryData, "err: open binary_test/demo_file.txt: The system cannot find the file specified."), w.String(),
этот assert зависит от платформы запуска, на маке текст будет другой

2023-09-20 14:46 UTC, tmvrus commented on internal/agent/agentcommands/createdata_test.go
> +		enterBinaryData, "err: open binary_test/demo_file.txt: The system cannot find the file specified."), w.String(),
этот assert зависит от платформы запуска, на маке текст будет другой

2023-09-20 14:46 UTC, tmvrus commented on internal/agent/agentcommands/grpcagent/grpcagent_test.go
> +	ga, err = NewGRPCAgent("localhost:8080", "")
ga вычисляется но не используется, можно заменить на _, err =  NewGRPCAgent("localhost:8080", "")

2023-09-20 14:46 UTC, tmvrus commented on internal/agent/agentcommands/auth.go
> +	fields, err := ac.reader.GetUserFields()
не проверяется ошибка

2023-09-20 14:46 UTC, tmvrus commented on internal/agent/agentcommands/auth.go
> +	fields, err := ac.reader.GetUserFields()
не проверяется ошибка

2023-09-20 14:46 UTC, tmvrus commented on internal/storage/sqlstorage/users.go
> +	Conn *sql.DB
все методы Conn *sql.DB будут доступны так как поле публичное, обычно это не то что нужно

2023-09-20 14:46 UTC, tmvrus commented on internal/storage/sqlstorage/users.go
> +		if pgErr, ok := err.(*pgconn.PgError); ok && pgErr.Code == "23505" {
для таких проверок есть errors.As, материал 3го спринта

2023-09-20 14:46 UTC, tmvrus commented on internal/server/auth.go
> +func generateRandom(size int) ([]byte, error) {
везде где эта ф-и вызывается, ей передается загадочное число 32, зачем тогда size в сигнатуре если размер фактически не меняется

2023-09-20 14:46 UTC, tmvrus commented on internal/storage/grpctypeconvert.go
> +}
эти сущности публичные но без документации

2023-09-20 14:46 UTC, tmvrus commented on internal/storage/interfaces.go
>  type BinaryDataRepository interface {
публичные сущности без документации

2023-09-20 14:46 UTC, tmvrus commented on internal/agent/agentcommands/openrecord.go
> +	defer f.Close()
не стоит игнорировать обработку потенциальных ошибок

2023-09-20 14:46 UTC, tmvrus commented on internal/agent/agentcommands/openrecord.go
> +	bd := v.(storage.BinaryData)
делать type assert без проверки типа - плохая практика, тем более в этой ф-и можно корректно завершиться с ошибкой

2023-09-20 14:46 UTC, tmvrus commented on internal/agent/agentwriter/agentwriter.go
> +}
не стоит игнорировать обработку потенциальныйх ошибок

2023-09-20 14:46 UTC, tmvrus commented on cmd/agent/agent.go
> +	fmt.Printf("Build version: %s\nBuild date: %s\nBuild commit: %s\n", buildVersion, buildDate, buildCommit)
не вполне ясно каким образом сюда попадет информация о сборке

2023-09-20 14:46 UTC, tmvrus commented on cmd/server/server.go
> +	log.Fatal(serverGRPC.Serve(listen))
вот так делать не нужно, Fatal будет вызываться в любом случае - была ошибки или нет

2023-09-20 14:46 UTC, tmvrus commented on internal/grpcserver/grpcserver.go
> +		log.Fatal(err)
зачем вызывать Fatal если можно вернуть ошибку?

2023-09-20 14:46 UTC, tmvrus commented on internal/grpcserver/grpcserver.go
>  		return nil, fmt.Errorf("login and password fields can not be empty")
для этих целей у GRPC есть волне конкретный код - InvalidArgument

2023-09-20 14:46 UTC, tmvrus commented on internal/server/auth.go
> +	s.authUsers[uToken] = *newUser
в настоящих приложениях так делать нельзя, конкурентная запись в map вызывает панику, race condition это материал 4 спринта

2023-09-20 14:46 UTC, tmvrus commented on internal/server/auth.go
> +	s.authUsers[uToken] = *bdUser
в настоящих приложениях так делать нельзя, конкурентная запись в map вызывает панику, race condition это материал 4 спринта

2023-09-20 14:46 UTC, tmvrus commented on internal/storage/sqlstorage/bankdata.go
> +		}
конструкцию 
```go
if x {
  return y
} elese {
  return z
}
```
всегда можно переписать без else, это повышает читаемость

```go
if x {
  return y
}
  return z
```

2023-09-20 14:46 UTC, tmvrus commented on internal/storage/sqlstorage/bankdata.go
> +	}
потерялась ошибка

2023-09-20 14:46 UTC, tmvrus commented on internal/storage/sqlstorage/binarydata.go
> +		return nil, nil
потерялась ошибка

2023-09-29 17:00 UTC, firesworder commented on internal/agent/agentcommands/updatedata_test.go
> +		enterBinaryData, "err: open binary_test/demo_file.txt: The system cannot find the file specified."), w.String(),
Исправил

2023-09-29 17:00 UTC, firesworder commented on internal/agent/agentcommands/createdata_test.go
> +		enterBinaryData, "err: open binary_test/demo_file.txt: The system cannot find the file specified."), w.String(),
Исправил

2023-09-29 17:02 UTC, firesworder commented on internal/agent/agentcommands/grpcagent/grpcagent_test.go
> +	ga, err = NewGRPCAgent("localhost:8080", "")
Исправил

2023-10-05 19:14 UTC, bambruysk approved these changes
Много тестов - понравилось. Интересная организация клиента(он же агент))) 
Принято

2023-10-05 19:14 UTC, bambruysk commented on cmd/agent/agent.go
> +	"log"
Нужно правильно сортировать импорты - сначал стандартную библиотеу, потом через пустиуцю строку остальное. потом еще через пустую строку совбственные пакеты

2023-10-05 19:14 UTC, bambruysk commented on internal/agent/agentcommands/grpcagent/methods.go
> +		context.Background(), metadata.New(map[string]string{ctxTokenParam: a.userToken}))
Это вероятно было бы удобно положить в интерсептор или просто отдельный метод

2023-10-05 19:14 UTC, bambruysk commented on internal/mocks/server.go
> +
Моки можно было бы и сгенерировать

2023-10-12 08:41 UTC, merged